//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavSistemiSon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_İstatistik
    {
        public int ID { get; set; }
        public Nullable<int> SoruID { get; set; }
        public Nullable<int> SınavID { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
