//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavSistemiSon
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public Nullable<int> rolID { get; set; }
        public int ID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public int Expr4 { get; set; }
        public int Expr5 { get; set; }
        public Nullable<int> KisiID { get; set; }
        public int Expr6 { get; set; }
    }
}
